#!/usr/bin/env python3
"""
Traffic Analytics Data Analysis Script
Analyzes the output from your traffic detection system
"""

import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta

def load_and_analyze_data():
    """Load JSON data and perform comprehensive analysis"""
    
    # Load JSON data generated by your Vision system
    with open('data/traffic_analytics.json', 'r') as f:
        data = json.load(f)
    
    print("=" * 80)
    print("TRAFFIC ANALYTICS DATA ANALYSIS REPORT")
    print("=" * 80)
    print()
    
    # Basic statistics
    total_frames = len(data)
    print(f"📊 Dataset Overview:")
    print(f"   • Total frames processed: {total_frames}")
    
    if total_frames > 0:
        first_timestamp = data[0]['timestamp']
        last_timestamp = data[-1]['timestamp']
        duration = last_timestamp - first_timestamp
        
        print(f"   • Duration: {duration:.2f} seconds ({duration/60:.2f} minutes)")
        print(f"   • Processing rate: {total_frames/duration:.2f} FPS")
    
    print()
    
    # Lane-wise analysis
    print("🚗 Lane-wise Vehicle Detection:")
    print("-" * 80)
    
    lanes = ['North Entry', 'South Entry', 'East Entry', 'West Entry']
    lane_stats = {lane: {'max_density': 0, 'total_vehicles': 0, 'frames_with_vehicles': 0} for lane in lanes}
    
    for frame_data in data:
        for lane in lanes:
            lane_info = frame_data['lane_data'][lane]
            density = lane_info['current_density']
            
            # Update max density
            if density > lane_stats[lane]['max_density']:
                lane_stats[lane]['max_density'] = density
            
            # Count frames with vehicles
            if density > 0:
                lane_stats[lane]['frames_with_vehicles'] += 1
            
            # Get total vehicles from cumulative stats
            cumulative = lane_info['cumulative_stats']
            total = sum(cumulative.values())
            if total > lane_stats[lane]['total_vehicles']:
                lane_stats[lane]['total_vehicles'] = total
    
    for lane, stats in lane_stats.items():
        print(f"\n{lane}:")
        print(f"   • Total vehicles detected: {stats['total_vehicles']}")
        print(f"   • Max density: {stats['max_density']} vehicles")
        print(f"   • Frames with vehicles: {stats['frames_with_vehicles']} / {total_frames} ({stats['frames_with_vehicles']/total_frames*100:.1f}%)")
    
    print()
    print("-" * 80)
    
    # Vehicle type breakdown
    print("\n🚙 Vehicle Type Distribution:")
    print("-" * 80)
    
    vehicle_types = ['car', 'motorcycle', 'bus', 'truck']
    type_totals = {vtype: 0 for vtype in vehicle_types}
    
    for lane in lanes:
        # Get the last frame's cumulative stats (should have highest counts)
        last_frame = data[-1]['lane_data'][lane]['cumulative_stats']
        for vtype in vehicle_types:
            type_totals[vtype] += last_frame[vtype]
    
    total_vehicles = sum(type_totals.values())
    
    for vtype, count in type_totals.items():
        percentage = (count / total_vehicles * 100) if total_vehicles > 0 else 0
        print(f"   • {vtype.capitalize()}: {count} ({percentage:.1f}%)")
    
    print(f"\n   Total vehicles across all lanes: {total_vehicles}")
    
    # Temporal analysis
    print("\n⏱️  Temporal Analysis:")
    print("-" * 80)
    
    # Extract density time series for each lane
    time_series = {lane: [] for lane in lanes}
    timestamps = []
    
    for frame_data in data:
        timestamps.append(frame_data['timestamp'])
        for lane in lanes:
            density = frame_data['lane_data'][lane]['current_density']
            time_series[lane].append(density)
    
    # Calculate statistics
    for lane in lanes:
        densities = np.array(time_series[lane])
        non_zero = densities[densities > 0]
        
        print(f"\n{lane}:")
        print(f"   • Mean density: {np.mean(densities):.2f}")
        print(f"   • Max density: {np.max(densities)}")
        print(f"   • Std deviation: {np.std(densities):.2f}")
        if len(non_zero) > 0:
            print(f"   • Mean when active: {np.mean(non_zero):.2f}")
    
    # Detection quality analysis
    print("\n\n⚠️  DETECTION QUALITY ASSESSMENT:")
    print("=" * 80)
    
    if total_vehicles < 10:
        print("❌ LOW DETECTION COUNT DETECTED!")
        print("\nPossible Issues:")
        print("   1. ROI (Region of Interest) may not be properly aligned with traffic flow")
        print("   2. YOLO confidence threshold may be too high (try 0.20-0.25)")
        print("   3. Camera angle may require perspective transformation")
        print("   4. Model may need fine-tuning for this specific scenario")
        print("\nRecommended Actions:")
        print("   • Verify ROI boundaries cover actual vehicle paths")
        print("   • Lower detection confidence threshold")
        print("   • Test with different video samples")
        print("   • Add preprocessing (contrast enhancement, dehazing)")
        print("   • Consider fine-tuning YOLO on similar camera angles")
    
    processing_speed = total_frames / duration if duration > 0 else 0
    if processing_speed < 15:
        print("\n⚠️  LOW PROCESSING SPEED DETECTED!")
        print(f"   Current: {processing_speed:.2f} FPS")
        print(f"   Target: 15-30 FPS for real-time operation")
        print("\nOptimization Suggestions:")
        print("   • Enable GPU acceleration (CUDA)")
        print("   • Use YOLOv8n (nano) instead of larger models")
        print("   • Implement frame skipping (process every 2nd/3rd frame)")
        print("   • Convert model to TensorRT for faster inference")
        print("   • Process only ROI regions instead of full frame")
    
    print("\n" + "=" * 80)
    
    return {
        'total_frames': total_frames,
        'duration': duration,
        'fps': processing_speed,
        'lane_stats': lane_stats,
        'vehicle_types': type_totals,
        'time_series': time_series
    }

def generate_recommendations():
    """Generate specific actionable recommendations"""
    
    print("\n\n🎯 IMMEDIATE ACTION ITEMS:")
    print("=" * 80)
    
    recommendations = [
        {
            'priority': 'CRITICAL',
            'task': 'Debug Detection Accuracy',
            'actions': [
                'Visualize YOLO detections on sample frames',
                'Check ROI alignment with actual vehicle paths',
                'Test with conf_threshold=0.20',
                'Verify camera calibration and perspective'
            ]
        },
        {
            'priority': 'HIGH',
            'task': 'Improve Processing Speed',
            'actions': [
                'Enable GPU if available (nvidia-smi to check)',
                'Use YOLOv8n.pt instead of larger models',
                'Implement async processing pipeline',
                'Profile code to find bottlenecks'
            ]
        },
        {
            'priority': 'MEDIUM',
            'task': 'Add Advanced Tracking',
            'actions': [
                'Integrate DeepSORT for multi-object tracking',
                'Implement unique vehicle ID assignment',
                'Track vehicle trajectories across frames',
                'Calculate entry-exit correlations'
            ]
        },
        {
            'priority': 'MEDIUM',
            'task': 'Enhance Analytics',
            'actions': [
                'Implement speed estimation',
                'Add queue length calculation',
                'Build congestion detection algorithm',
                'Create predictive models (LSTM)'
            ]
        }
    ]
    
    for i, rec in enumerate(recommendations, 1):
        print(f"\n{i}. [{rec['priority']}] {rec['task']}")
        for action in rec['actions']:
            print(f"   □ {action}")
    
    print("\n" + "=" * 80)

def create_visualization_code():
    """Generate sample visualization code"""
    
    print("\n\n📊 SAMPLE VISUALIZATION CODE:")
    print("=" * 80)
    
    code = '''
import matplotlib.pyplot as plt
import seaborn as sns

# Set style
sns.set_style("whitegrid")

# Create figure with subplots
fig, axes = plt.subplots(2, 2, figsize=(15, 10))

# 1. Lane density over time
for lane in ['North Entry', 'South Entry', 'East Entry', 'West Entry']:
    axes[0, 0].plot(time_series[lane], label=lane)
axes[0, 0].set_title('Traffic Density Over Time')
axes[0, 0].set_xlabel('Frame')
axes[0, 0].set_ylabel('Vehicle Count')
axes[0, 0].legend()

# 2. Vehicle type distribution
vehicle_counts = [type_totals['car'], type_totals['motorcycle'], 
                  type_totals['bus'], type_totals['truck']]
axes[0, 1].bar(['Cars', 'Motorcycles', 'Buses', 'Trucks'], vehicle_counts)
axes[0, 1].set_title('Vehicle Type Distribution')
axes[0, 1].set_ylabel('Count')

# 3. Lane comparison
lane_totals = [lane_stats[lane]['total_vehicles'] for lane in lanes]
axes[1, 0].barh(lanes, lane_totals)
axes[1, 0].set_title('Total Vehicles by Lane')
axes[1, 0].set_xlabel('Vehicle Count')

# 4. Processing performance
axes[1, 1].text(0.5, 0.5, f'Processing Speed\\n{fps:.2f} FPS', 
                ha='center', va='center', fontsize=20)
axes[1, 1].set_title('System Performance')
axes[1, 1].axis('off')

plt.tight_layout()
plt.savefig('traffic_analysis.png', dpi=300, bbox_inches='tight')
plt.show()
'''
    
    print(code)
    print("\n" + "=" * 80)

if __name__ == "__main__":
    try:
        # Analyze data
        results = load_and_analyze_data()
        
        # Generate recommendations
        generate_recommendations()
        
        # Show visualization code
        create_visualization_code()
        
        print("\n✅ Analysis complete!")
        print("\n💡 Tip: Run this script with matplotlib installed to generate visualizations")
        print("   pip install matplotlib seaborn pandas")
        
    except FileNotFoundError:
        print("❌ Error: Could not find data files")
        print("Make sure the JSON and CSV files are in the correct location")
    except Exception as e:
        print(f"❌ Error during analysis: {str(e)}")
        import traceback
        traceback.print_exc()
