"""initial

Revision ID: 39b76172ad74
Revises: 
Create Date: 2026-04-05 21:31:51.018541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39b76172ad74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_config',
    sa.Column('camera_id', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('camera_type', sa.String(length=20), nullable=True),
    sa.Column('paired_camera', sa.String(length=50), nullable=True),
    sa.Column('distance_to_pair_km', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('speed_limit_kmh', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('camera_id')
    )
    op.create_table('fine_rules',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('violation_type', sa.String(length=50), nullable=False),
    sa.Column('base_fine', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('repeat_multiplier', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('rule_id'),
    sa.UniqueConstraint('violation_type')
    )
    op.create_table('lanes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vehicles',
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('owner_phone', sa.String(length=15), nullable=False),
    sa.Column('owner_email', sa.String(length=100), nullable=True),
    sa.Column('vehicle_type', sa.String(length=20), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('plate_number')
    )
    op.create_table('daily_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('day_of_week', sa.String(length=15), nullable=True),
    sa.Column('lane_id', sa.Integer(), nullable=True),
    sa.Column('total_vehicles', sa.Integer(), nullable=True),
    sa.Column('vehicle_breakdown', sa.JSON(), nullable=True),
    sa.Column('avg_wait_time', sa.Float(), nullable=True),
    sa.Column('peak_hours', sa.JSON(), nullable=True),
    sa.Column('total_violations', sa.Integer(), nullable=True),
    sa.Column('avg_traffic_density', sa.Float(), nullable=True),
    sa.Column('avg_vehicle_speed', sa.Float(), nullable=True),
    sa.Column('busiest_hour', sa.Integer(), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lane_id'], ['lanes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_statistics_date'), 'daily_statistics', ['date'], unique=False)
    op.create_table('hourly_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('lane_id', sa.Integer(), nullable=True),
    sa.Column('total_vehicles', sa.Integer(), nullable=True),
    sa.Column('vehicle_breakdown', sa.JSON(), nullable=True),
    sa.Column('avg_wait_time', sa.Float(), nullable=True),
    sa.Column('max_wait_time', sa.Float(), nullable=True),
    sa.Column('min_wait_time', sa.Float(), nullable=True),
    sa.Column('total_violations', sa.Integer(), nullable=True),
    sa.Column('peak_hour', sa.Boolean(), nullable=True),
    sa.Column('avg_vehicle_speed', sa.Float(), nullable=True),
    sa.Column('traffic_density', sa.Float(), nullable=True),
    sa.Column('congestion_level', sa.Enum('LOW', 'MODERATE', 'HEAVY', 'CRITICAL', name='congestionlevel'), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lane_id'], ['lanes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hourly_statistics_datetime'), 'hourly_statistics', ['datetime'], unique=False)
    op.create_table('signal_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('lane_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('adaptive_mode', sa.Boolean(), nullable=True),
    sa.Column('queue_length', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lane_id'], ['lanes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_states_timestamp'), 'signal_states', ['timestamp'], unique=False)
    op.create_table('traffic_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('lane_id', sa.Integer(), nullable=True),
    sa.Column('active_vehicles', sa.Integer(), nullable=True),
    sa.Column('congestion_level', sa.Enum('LOW', 'MODERATE', 'HEAVY', 'CRITICAL', name='congestionlevel'), nullable=True),
    sa.Column('avg_speed', sa.Float(), nullable=True),
    sa.Column('violations_count', sa.Integer(), nullable=True),
    sa.Column('avg_wait_time', sa.Float(), nullable=True),
    sa.Column('signal_state', sa.String(length=20), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lane_id'], ['lanes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_snapshots_timestamp'), 'traffic_snapshots', ['timestamp'], unique=False)
    op.create_table('vehicle_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('frame_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('lane_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_class', sa.Enum('CAR', 'MOTORCYCLE', 'BUS', 'TRUCK', 'AUTO', 'BICYCLE', 'PEDESTRIAN', 'OTHER', name='vehicleclass'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('bbox_x1', sa.Integer(), nullable=True),
    sa.Column('bbox_y1', sa.Integer(), nullable=True),
    sa.Column('bbox_x2', sa.Integer(), nullable=True),
    sa.Column('bbox_y2', sa.Integer(), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lane_id'], ['lanes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_detections_timestamp'), 'vehicle_detections', ['timestamp'], unique=False)
    op.create_table('violations',
    sa.Column('violation_id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('violation_type', sa.String(length=50), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('video_path', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('fine_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fine_status', sa.String(length=20), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['plate_number'], ['vehicles.plate_number'], ),
    sa.PrimaryKeyConstraint('violation_id')
    )
    op.create_index(op.f('ix_violations_fine_status'), 'violations', ['fine_status'], unique=False)
    op.create_index(op.f('ix_violations_plate_number'), 'violations', ['plate_number'], unique=False)
    op.create_index(op.f('ix_violations_timestamp'), 'violations', ['timestamp'], unique=False)
    op.create_table('wait_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('lane_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_type', sa.Enum('CAR', 'MOTORCYCLE', 'BUS', 'TRUCK', 'AUTO', 'BICYCLE', 'PEDESTRIAN', 'OTHER', name='vehicleclass'), nullable=True),
    sa.Column('wait_time_seconds', sa.Float(), nullable=True),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('stopped_duration', sa.Float(), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lane_id'], ['lanes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wait_times_timestamp'), 'wait_times', ['timestamp'], unique=False)
    op.create_table('speed_tracking',
    sa.Column('tracking_id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('entry_camera', sa.String(length=50), nullable=False),
    sa.Column('entry_timestamp', sa.DateTime(), nullable=False),
    sa.Column('exit_camera', sa.String(length=50), nullable=True),
    sa.Column('exit_timestamp', sa.DateTime(), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('average_speed_kmh', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('speed_limit_kmh', sa.Integer(), nullable=True),
    sa.Column('is_violation', sa.Boolean(), nullable=True),
    sa.Column('violation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.violation_id'], ),
    sa.PrimaryKeyConstraint('tracking_id')
    )
    op.create_index(op.f('ix_speed_tracking_entry_timestamp'), 'speed_tracking', ['entry_timestamp'], unique=False)
    op.create_index(op.f('ix_speed_tracking_plate_number'), 'speed_tracking', ['plate_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speed_tracking_plate_number'), table_name='speed_tracking')
    op.drop_index(op.f('ix_speed_tracking_entry_timestamp'), table_name='speed_tracking')
    op.drop_table('speed_tracking')
    op.drop_index(op.f('ix_wait_times_timestamp'), table_name='wait_times')
    op.drop_table('wait_times')
    op.drop_index(op.f('ix_violations_timestamp'), table_name='violations')
    op.drop_index(op.f('ix_violations_plate_number'), table_name='violations')
    op.drop_index(op.f('ix_violations_fine_status'), table_name='violations')
    op.drop_table('violations')
    op.drop_index(op.f('ix_vehicle_detections_timestamp'), table_name='vehicle_detections')
    op.drop_table('vehicle_detections')
    op.drop_index(op.f('ix_traffic_snapshots_timestamp'), table_name='traffic_snapshots')
    op.drop_table('traffic_snapshots')
    op.drop_index(op.f('ix_signal_states_timestamp'), table_name='signal_states')
    op.drop_table('signal_states')
    op.drop_index(op.f('ix_hourly_statistics_datetime'), table_name='hourly_statistics')
    op.drop_table('hourly_statistics')
    op.drop_index(op.f('ix_daily_statistics_date'), table_name='daily_statistics')
    op.drop_table('daily_statistics')
    op.drop_table('vehicles')
    op.drop_table('lanes')
    op.drop_table('fine_rules')
    op.drop_table('camera_config')
    # ### end Alembic commands ###
